# nextjs dockerfile with dev step. package manager is pnpm
FROM node:20 as modif-pdf-dev

WORKDIR /app

RUN apt-get -qq update && \
    apt-get -qq dist-upgrade && \
    apt-get -qq install pdftk && \
    apt-get -qq clean

RUN corepack enable
RUN corepack prepare pnpm@latest --activate

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 3000

CMD pnpm dev


